permalink:           tutorials/:title.html
gems: [jekyll-paginate]

# Setup
title:               'argonjs documentation'
tagline:             'Documentation'
description:         'This site contains documentation for web developers using <a href="http://argonjs.io" target="_blank">argon.js</a> to add AR content to a web application.'
#url:                 http://docs.argonjs.io
baseurl:             '/'
#baseurl:             'http://docs.argonjs.io/'
paginate:            5


exclude: ['Rakefile', 'LICENSE.txt', 'CLA.md', 'CONTRIBUTING.md', 'README.md', "node_modules", "package.json"]

# About/contact
author:
  name:
  email:

# Custom vars
version:             1.0.0
